### ISSUE TITLE
Better readme.md.

### ISSUE THREAD

**Issue by Atharv-Attri** [harshildarji/location_based_cryptography#1]
The readme should be better. I really like the program, but I don't understand how to use it. I propose that you improve the readme.md to explain how other people can use it. Improving the readme.md may include that you explain how the program works, how other people can use it, and maybe show it in use.

**Comment by harshildarji** [comment]
Well, currently I am working on my [master's thesis](https://harshildarji.github.io/thesis/), so I cannot work on your request right now, but I will keep this in mind for the future.

**Comment by Atharv-Attri** [comment]
Ok, thanks!
