### ISSUE TITLE
Should be packaged as a module

### ISSUE THREAD

**Issue by Atharv-Attri** [harshildarji/location_based_cryptography#2]
Can you consider packaging the program as a PyPi package? This would help integrate the code in other software immensely.

**Comment by harshildarji** [comment]
As I mentioned in issue #1, I will do this in the future.

**Comment by harshildarji** [comment]
@Atharv-Attri Hey, I have published this repo as PyPI package at https://pypi.org/project/locationcrypto/.
Apologies for the long delay.
